- name: Import platform tasks (Arch Linux)
  ansible.builtin.import_tasks: '{{ role_path }}/tasks/archlinux.yml'
  when: ansible_facts["distribution"] == 'Archlinux'

- name: Import platform tasks (macOS)
  ansible.builtin.import_tasks: '{{ role_path }}/tasks/macos.yml'
  when: ansible_facts["distribution"] == 'MacOSX'

- name: Ensure Jujutsu config directory exists
  ansible.builtin.file:
    path: '{{ ansible_facts["env"].HOME }}/.config/jj/conf.d'
    state: directory

- name: Link base config file into place
  ansible.builtin.file:
    src: '{{ role_path }}/files/00-base.toml'
    dest: '{{ ansible_facts["env"].HOME }}/.config/jj/conf.d/00-base.toml'
    state: link

- name: Place file to source jj zsh integration and completion
  ansible.builtin.file:
    src: '{{ role_path }}/files/jj.zsh'
    dest: '{{ zsh_env.ZSHEXTRAS }}/jj.zsh'
    state: link
